# ABOUTME: V1 alarm/fault name tables — shared by V1 model classes (Unit 10b).
# ABOUTME: Low-power tables mirror ConnConstantsV2.lowPowerWarnNames / lowPowerFaultNames.
# ABOUTME: High-power tables mirror ConnectConstants.alarmInfoNames / faultInfoNames.
# ABOUTME: Spelling quirks from APK string resources preserved (e.g. "valtage", "leakage", "insulation").

# ── Low-power tables (AC200L, AC200PL) ────────────────────────────────

LOW_POWER_WARN_NAMES: dict[int, list[str | None]] = {
    1: [
        "Grid Voltage High",
        "Grid Voltage Low",
        "Grid Frequency High",
        "Grid Frequency Low",
        "Grid Oscillation",
        "Networking Operation Abnormal",
        "Grid Connection Fault",
        "Accessory Malfunction",
        "PV Configuration Error",
        "Grid 2 Voltage High",
        "Grid 2 Voltage Low",
        "Grid 2 Frequency High",
        "Grid 2 Frequency Low",
        "Grid 2 Oscillation",
        "Grid Not Connected",
    ],
    2: [
        "Battery Pack Communication Abnormal",
        "IoT Communication Error",
        "UPS Input Overvoltage",
        "UPS Input Undervoltage",
        "UPS Input Overcurrent",
        "UPS Input Overtemperature",
        "UPS Precharge Fault",
        "UPS Hardware Fault",
    ],
}

LOW_POWER_FAULT_NAMES: dict[int, list[str | None]] = {
    1: [
        "Inverter Overload",
        "Inverter Over Temperature",
        "Inverter Short Circuit",
        "Inverter Output Fault",
        "LLC Output Error",
        "Bus Over Voltage/Hardware Bus Over Voltage",
        "BUS Low Voltage",
        "Hardware Inverter Overcurrent",
        "Hardware Input Overcurrent",
        "Battery Voltage High/Hardware Battery Over Voltage",
        "Battery Voltage Low",
        "Main Relay Failure",
        "Grid Relay Failure",
        "Calibration Fail",
        "Auxiliary Battery Malfunction",
        "Fan Error",
    ],
    2: [
        "Multihost Error",
        "Phase Loss",
        "Multi-machine Communication Abnormal",
        "Multi-machine Synchronization Abnormal",
        "Multi-machine Configuration Abnormal",
        "Generator Voltage Abnormal",
        "System Initialization Failure",
        "Parallel Relay Failure",
        "Grid Input Overcurrent",
        "System Overload",
        "DC Output Overload",
        "Inverter Low Temperature",
    ],
    3: [
        "PV1 Over Voltage",
        "PV2 Over Voltage",
        "PV3 Over Voltage",
        "PV1 Overcurrent",
        "PV2 Overcurrent",
        "PV3 Overcurrent",
        "PV1 Over Temperature",
        "PV2 Over Temperature",
        "PV3 Over Temperature",
        "PV Precharge Fault",
        "PV1 Hardware Error",
        "PV2 Hardware Error",
        "PV3 Hardware Error",
        "PV Insulation Resistance Fault",
    ],
    4: [
        "PV4 Over Voltage",
        "PV4 Overcurrent",
        "PV4 Over Temperature",
        "PV4 Hardware Error",
        "PV1 Low Temperature",
        "PV2 Low Temperature",
        "PV3 Low Temperature",
        "PV4 Low Temperature",
    ],
    5: [
        "DC Output Short Circuit",
        "DC Output Voltage High",
        "DC Output Current High",
        "DC Output Over Temperature",
        "DC Output Failure",
        "BMS Communication Failure",
        "Inverter String Communication Failure",
        "RTC Error",
        "EEPROM Error",
        "BMS System Fault",
        "Controller Temperature Too High",
        "Zero Drift Abnormal (DSP)",
        "DC Output Low Temperature",
        "Leakage Current Fault",
        "Insulation Resistance Failure",
    ],
}

# ── High-power tables (EB3A, AC200M, AC300, AC500 — V1Base default) ──

CONNECT_CONSTANTS_ALARM_NAMES: dict[int, list[str | None]] = {
    1: [
        "Grid voltage high",
        "Grid voltage low",
        "Grid frequency high",
        "Grid frequency low",
        "Grid oscillation",
        "Meter communication failure",
        "PV Over Voltage",
        "PV Low Voltage",
        "Generator voltage abnormal",
    ],
}

CONNECT_CONSTANTS_FAULT_NAMES: dict[int, list[str | None]] = {
    1: [
        "Inverter Over Load",
        "Inverter Overheated",
        "Battery Over Voltage",
        "Battery Low Voltage",
        "Inverter Output Fault",
        "BMS Communication Error",
        "Voltage Sensor Error",
        "Current Sampling Sensor Error",
        "Trans Temperature High",
        "Controller Temperature High",
        "Device Temperature High",
        "Battery Pack Error",
        "Battery Disconnected",
        "Fan Error",
        "Main Relay Failure",
        "Grid Relay Failure",
    ],
    2: [
        "Charger Overload",
        "Charger Failure",
        "Second Charger Failure",
        "Multi Main Station Failure",
        "Break Phase Error",
        "Multi Communication Error",
        "Multi Synchronization Error",
        "Multi Configuration Error",
        "DC Output Over Voltage",
        "DC Output Over Current",
        "DC Output Fail",
        "Calibration Fail",
        "Leakage Current Detecting Fail",
        "Insulation Detecting Fail",
        None,
        None,
    ],
    3: [
        "Charging Temperature High",
        "Discharging Temperature High",
        "Charging Temperature Low",
        "Discharging Temperature Low",
        "Overall Battery Overvoltage Protection",
        "Overall Battery Undervoltage Protection",
        "Single Battery Voltage High",
        "Single Battery Voltage Low",
        "Overcurrent Protection 1",
        "Overcurrent Protection 2",
        "Overcurrent Protection 3",
        "Overcurrent Protection 4",
        "Precharge Failure",
        "Short Circuit Protection",
        None,
        None,
    ],
    4: [
        "Bus Over Voltage",
        "Bus Low Voltage",
        "Hardware Bus Over Voltage",
        "Hardware Battery Over Voltage",
        "Hardware Inverter Over Current",
        "Hardware Input Over Current",
        "Calibration Fail",
        "Grid Error",
        "Temperature Over High",
        "Battery Low Voltage",
        "Battery Over Voltage",
        "PV1 Voltage Low",
        "PV2 Voltage Low",
        "PV1 Voltage High",
        "PV2 Voltage High",
        "Inverter Over Load",
    ],
    5: [
        "GFCI Hardware Circuit Error",
        "GFCI Error",
        "PV1 ISO Error",
        "PV2 ISO Error",
        "First Bidirectional DC Temperature Fault",
        "Second Bidirectional DC Temperature Fault",
        "R Temperature Error",
        "S Temperature Error",
        "T Temperature Error",
        "BUS Sampling Error",
        "Phase Error",
        "Fan Error",
        "LLC Output Over Voltage",
        None,
        None,
        None,
    ],
}
